version: "3"

services:
  mysite:
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - .:/db
    command: >
            sh -c "python manage.py wait_for_db &&
                   python manage.py migrate &&
                   gunicorn --access-logfile /var/log/gunicorn_access.log --error-logfile /var/log/gunicorn_error.log --bind 0.0.0.0:8001 mysite.wsgi"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

